### ISSUE TITLE
linux config line

### ISSUE THREAD

**Issue by mike112112** [Speentie8081/HardScene_Minecraft-RemoteTerminal#6]
The code at line 223 HardSceneBukkit.java is making linux not to start java executable from the config for remotestart because of  "" so it needs manually editing every restart from "/usr/bin/java" in config to /usr/bin/java. I understand it because of windows needing "" when there is a gap between words, is it maybe possible for it to detect the os instead?

**Comment by Speentie8081** [comment]
That is odd, because it works just fine on our linux server. I have been noticing you making those changes to the remotestart config lately and have already been thinking about making it so you can save the config changes so it doesn't overwrite every restart. Let me see what I can do and I will get back to you on this.

**Comment by Speentie8081** [comment]
Closed with [https://www.spigotmc.org/resources/hardscene-remoteterminal.33149/update?update=324493](https://www.spigotmc.org/resources/hardscene-remoteterminal.33149/update?update=324493)

**Comment by mike112112** [comment]
thank you for your quick response and coding

**Comment by Speentie8081** [comment]
You can also reach me about this project at [https://devon.com.de/threads/rterminal-cpanel-minecraft-webpanel.50/](https://devon.com.de/threads/rterminal-cpanel-minecraft-webpanel.50/) if you find that it is hard to get to me through github.

**Comment by Speentie8081** [comment]
The link is now [https://www.spigotmc.org/resources/hardscene-remoteterminal.33149/update?update=324499](https://www.spigotmc.org/resources/hardscene-remoteterminal.33149/update?update=324499) because the update I initially did was faulty lol. This is what happens when you release an update without ever testing it. It's working fine now.
